# Generated by Django 3.2.6 on 2022-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211229_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_chanel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
