# Generated by Django 3.2.6 on 2021-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211114_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Upload_image',
            field=models.ImageField(blank='True', default='sGoogle.png', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
