# Generated by Django 3.2.6 on 2021-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_project_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Upload_image',
            field=models.ImageField(blank=True, default='profiles/image.jpg', null=True, upload_to='profiles/'),
        ),
    ]
